const express = require('express');
const auth = require('../middleware/auth');
const User = require('../models/User');
const Block = require('../models/Block');
const MiningActivity = require('../models/MiningActivity');
const SupplyTracker = require('../models/SupplyTracker');

const router = express.Router();

// GET /api/user/profile - Get user profile
router.get('/profile', auth, async (req, res) => {
    try {
        const user = req.user;

        res.json({
            id: user._id,
            telegramId: user.telegramId,
            username: user.username,
            firstName: user.firstName,
            lastName: user.lastName,
            photoUrl: user.photoUrl,
            energy: user.energy,
            maxEnergy: user.maxEnergy,
            tokens: user.tokens,
            totalMined: user.totalMined,
            miningSessionsCount: user.miningSessionsCount,
            unlockedModes: user.unlockedModes,
            tonWalletAddress: user.tonWalletAddress,
            referralCode: user.referralCode,
            referralCount: user.referralCount,
            referralEarnings: user.referralEarnings,
            createdAt: user.createdAt
        });
    } catch (error) {
        console.error('Profile error:', error);
        res.status(500).json({ error: 'Failed to get profile' });
    }
});

// POST /api/user/energy/regen - Manually trigger energy regeneration
router.post('/energy/regen', auth, async (req, res) => {
    try {
        const user = req.user;
        // Energy is already regenerated by auth middleware
        res.json({
            energy: user.energy,
            maxEnergy: user.maxEnergy,
            lastUpdate: user.lastEnergyUpdate
        });
    } catch (error) {
        console.error('Energy regen error:', error);
        res.status(500).json({ error: 'Failed to regenerate energy' });
    }
});

// POST /api/user/energy/increase - Increase max energy by 2000
router.post('/energy/increase', auth, async (req, res) => {
    try {
        const user = req.user;
        const INCREASE_COST = 1000; // Costs 1000 tokens to increase max energy

        if (user.tokens < INCREASE_COST) {
            return res.status(400).json({
                error: 'Not enough tokens',
                required: INCREASE_COST,
                current: user.tokens
            });
        }

        user.maxEnergy += 2000;
        user.energy += 2000; // Also give the energy immediately
        user.tokens -= INCREASE_COST;
        await user.save();

        res.json({
            success: true,
            energy: user.energy,
            maxEnergy: user.maxEnergy,
            tokens: user.tokens
        });
    } catch (error) {
        console.error('Energy increase error:', error);
        res.status(500).json({ error: 'Failed to increase energy' });
    }
});

// GET /api/user/stats - Get blockchain-wide statistics
router.get('/stats', auth, async (req, res) => {
    try {
        const totalUsers = await User.countDocuments();
        const completedBlocks = await Block.countDocuments({ status: 'completed' });
        const tracker = await SupplyTracker.getInstance();

        const TOTAL_SUPPLY = 1_000_000_000;
        const totalMinted = tracker.totalMinted;
        const minedPercentage = Math.min((totalMinted / TOTAL_SUPPLY) * 100, 100);

        res.json({
            totalMined: Math.round(minedPercentage * 10) / 10,
            totalIssue: TOTAL_SUPPLY,
            blocksCreated: completedBlocks,
            totalHolders: totalUsers,
            startDate: '15 February',
            totalTokensMinted: Math.round(totalMinted * 100) / 100,
            remainingSupply: Math.round((TOTAL_SUPPLY - totalMinted) * 100) / 100
        });
    } catch (error) {
        console.error('Stats error:', error);
        res.status(500).json({ error: 'Failed to get stats' });
    }
});

// PUT /api/user/username - Update username
router.put('/username', auth, async (req, res) => {
    try {
        const { username } = req.body;

        if (!username || username.length < 3 || username.length > 20) {
            return res.status(400).json({ error: 'Username must be 3-20 characters' });
        }

        req.user.username = username;
        await req.user.save();

        res.json({ success: true, username: req.user.username });
    } catch (error) {
        console.error('Username update error:', error);
        res.status(500).json({ error: 'Failed to update username' });
    }
});

module.exports = router;
